import type { CheckoutTranslations } from "./types"

export const en: CheckoutTranslations = {
  address: {
    shippingAddress: "Shipping Address",
    billingAddress: "Billing address",
    edit: "Edit",
    continueToDelivery: "Continue to delivery",
    contact: "Contact",
    sameAddressText: "Billing and delivery address are the same.",
    savedAddressGreeting: "Hi {name}, do you want to use one of your saved addresses?",
    firstName: "First name",
    lastName: "Last name",
    addressLine: "Address",
    company: "Company",
    postalCode: "Postal code",
    city: "City",
    stateProvince: "State / Province",
    billingSameAsShipping: "Billing address same as shipping address",
    email: "Email",
    phone: "Phone",
    validEmail: "Enter a valid email address.",
  },
  delivery: {
    heading: "Delivery",
    edit: "Edit",
    shippingMethod: "Shipping method",
    howDelivered: "How would you like your order delivered",
    pickUpOrder: "Pick up your order",
    store: "Store",
    chooseStore: "Choose a store near you",
    continueToPayment: "Continue to payment",
    method: "Method",
  },
  payment: {
    heading: "Payment",
    edit: "Edit",
    continueToReview: "Continue to review",
    enterCardDetails: "Enter card details",
    paymentMethod: "Payment method",
    paymentDetails: "Payment details",
    card: "Card",
    giftCard: "Gift card",
  },
  review: {
    heading: "Review",
    termsText:
      "By clicking the Place Order button, you confirm that you have read, understand and accept our Terms of Use, Terms of Sale and Returns Policy and acknowledge that you have read Medusa Store’s Privacy Policy.",
    placeOrder: "Place order",
    selectPaymentMethod: "Select a payment method",
    loadingPaypal: "Loading PayPal…",
    paypalUnavailable: "PayPal unavailable",
  },
  summary: {
    inYourCart: "In your Cart",
    addPromotion: "Add Promotion Code(s)",
    apply: "Apply",
    promotionsApplied: "Promotion(s) applied:",
  },
}
