import type { CheckoutTranslations } from "./types"

export const da: CheckoutTranslations = {
  address: {
    shippingAddress: "Leveringsadresse",
    billingAddress: "Faktureringsadresse",
    edit: "Rediger",
    continueToDelivery: "Fortsæt til levering",
    contact: "Kontakt",
    sameAddressText: "Fakturerings- og leveringsadresse er ens.",
    savedAddressGreeting: "Hej {name}, vil du bruge en af dine gemte adresser?",
    firstName: "Fornavn",
    lastName: "Efternavn",
    addressLine: "Adresse",
    company: "Virksomhed",
    postalCode: "Postnummer",
    city: "By",
    stateProvince: "Region / Provins",
    billingSameAsShipping: "Faktureringsadresse er den samme som leveringsadresse",
    email: "E-mail",
    phone: "Telefon",
    validEmail: "Indtast en gyldig e-mailadresse.",
  },
  delivery: {
    heading: "Levering",
    edit: "Rediger",
    shippingMethod: "Leveringsmetode",
    howDelivered: "Hvordan vil du gerne have din ordre leveret",
    pickUpOrder: "Afhent din ordre",
    store: "Butik",
    chooseStore: "Vælg en butik i nærheden",
    continueToPayment: "Fortsæt til betaling",
    method: "Metode",
  },
  payment: {
    heading: "Betaling",
    edit: "Rediger",
    continueToReview: "Fortsæt til gennemgang",
    enterCardDetails: "Indtast kortoplysninger",
    paymentMethod: "Betalingsmetode",
    paymentDetails: "Betalingsoplysninger",
    card: "Kort",
    giftCard: "Gavekort",
  },
  review: {
    heading: "Gennemgang",
    termsText:
      "Ved at klikke på Afgiv ordre-knappen bekræfter du, at du har læst, forstår og accepterer vores Brugsbetingelser, Salgsbetingelser og Returpolitik, og at du har læst Medusa Stores Privatlivspolitik.",
    placeOrder: "Afgiv ordre",
    selectPaymentMethod: "Vælg en betalingsmetode",
    loadingPaypal: "Indlæser PayPal…",
    paypalUnavailable: "PayPal ikke tilgængeligt",
  },
  summary: {
    inYourCart: "I din kurv",
    addPromotion: "Tilføj rabatkode(r)",
    apply: "Anvend",
    promotionsApplied: "Anvendte kampagner:",
  },
}
