import type { CheckoutTranslations } from "./types"

export const de: CheckoutTranslations = {
  address: {
    shippingAddress: "Lieferadresse",
    billingAddress: "Rechnungsadresse",
    edit: "Bearbeiten",
    continueToDelivery: "Weiter zur Lieferung",
    contact: "Kontakt",
    sameAddressText: "Rechnungs- und Lieferadresse sind identisch.",
    savedAddressGreeting: "Hallo {name}, möchten Sie eine Ihrer gespeicherten Adressen verwenden?",
    firstName: "Vorname",
    lastName: "Nachname",
    addressLine: "Adresse",
    company: "Unternehmen",
    postalCode: "Postleitzahl",
    city: "Stadt",
    stateProvince: "Bundesland / Provinz",
    billingSameAsShipping: "Rechnungsadresse ist identisch mit Lieferadresse",
    email: "E-Mail",
    phone: "Telefon",
    validEmail: "Geben Sie eine gültige E-Mail-Adresse ein.",
  },
  delivery: {
    heading: "Lieferung",
    edit: "Bearbeiten",
    shippingMethod: "Versandmethode",
    howDelivered: "Wie soll Ihre Bestellung geliefert werden",
    pickUpOrder: "Bestellung abholen",
    store: "Filiale",
    chooseStore: "Wählen Sie eine Filiale in Ihrer Nähe",
    continueToPayment: "Weiter zur Zahlung",
    method: "Methode",
  },
  payment: {
    heading: "Zahlung",
    edit: "Bearbeiten",
    continueToReview: "Weiter zur Überprüfung",
    enterCardDetails: "Kartendaten eingeben",
    paymentMethod: "Zahlungsmethode",
    paymentDetails: "Zahlungsdetails",
    card: "Karte",
    giftCard: "Gutschein",
  },
  review: {
    heading: "Überprüfung",
    termsText:
      "Indem Sie auf den Button Bestellung aufgeben klicken, bestätigen Sie, dass Sie unsere Nutzungsbedingungen, Verkaufsbedingungen und Rückgabebedingungen gelesen haben, verstehen und akzeptieren, und dass Sie die Datenschutzrichtlinie des Medusa Stores gelesen haben.",
    placeOrder: "Bestellung aufgeben",
    selectPaymentMethod: "Zahlungsmethode auswählen",
    loadingPaypal: "PayPal wird geladen…",
    paypalUnavailable: "PayPal nicht verfügbar",
  },
  summary: {
    inYourCart: "In Ihrem Warenkorb",
    addPromotion: "Gutscheincode(s) hinzufügen",
    apply: "Anwenden",
    promotionsApplied: "Angewendete Aktion(en):",
  },
}
