import type { CheckoutTranslations } from "./types"

export const fr: CheckoutTranslations = {
  address: {
    shippingAddress: "Adresse de livraison",
    billingAddress: "Adresse de facturation",
    edit: "Modifier",
    continueToDelivery: "Continuer vers la livraison",
    contact: "Contact",
    sameAddressText: "L'adresse de facturation et de livraison sont identiques.",
    savedAddressGreeting: "Bonjour {name}, souhaitez-vous utiliser l'une de vos adresses enregistrées ?",
    firstName: "Prénom",
    lastName: "Nom",
    addressLine: "Adresse",
    company: "Société",
    postalCode: "Code postal",
    city: "Ville",
    stateProvince: "État / Province",
    billingSameAsShipping: "L'adresse de facturation est la même que l'adresse de livraison",
    email: "E-mail",
    phone: "Téléphone",
    validEmail: "Saisissez une adresse e-mail valide.",
  },
  delivery: {
    heading: "Livraison",
    edit: "Modifier",
    shippingMethod: "Mode de livraison",
    howDelivered: "Comment souhaitez-vous recevoir votre commande",
    pickUpOrder: "Retirer votre commande",
    store: "Magasin",
    chooseStore: "Choisissez un magasin près de chez vous",
    continueToPayment: "Continuer vers le paiement",
    method: "Méthode",
  },
  payment: {
    heading: "Paiement",
    edit: "Modifier",
    continueToReview: "Continuer vers la vérification",
    enterCardDetails: "Saisir les détails de la carte",
    paymentMethod: "Méthode de paiement",
    paymentDetails: "Détails de paiement",
    card: "Carte",
    giftCard: "Carte cadeau",
  },
  review: {
    heading: "Vérification",
    termsText:
      "En cliquant sur le bouton Passer la commande, vous confirmez avoir lu, compris et accepté nos Conditions d'utilisation, Conditions de vente et Politique de retour, et avoir pris connaissance de la Politique de confidentialité de Medusa Store.",
    placeOrder: "Passer la commande",
    selectPaymentMethod: "Sélectionner un mode de paiement",
    loadingPaypal: "Chargement de PayPal…",
    paypalUnavailable: "PayPal indisponible",
  },
  summary: {
    inYourCart: "Dans votre panier",
    addPromotion: "Ajouter un code promo",
    apply: "Appliquer",
    promotionsApplied: "Promotion(s) appliquée(s) :",
  },
}
